// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6dXQG3AWe52nWUkiSjwXSfsfPwj3BR4E',
    appId: '1:78588377384:web:473aa615520b1b0152381d',
    messagingSenderId: '78588377384',
    projectId: 'sahhaapp-6e10d',
    authDomain: 'sahhaapp-6e10d.firebaseapp.com',
    databaseURL: 'https://sahhaapp-6e10d-default-rtdb.firebaseio.com',
    storageBucket: 'sahhaapp-6e10d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXfKLktc4LEaQ98US6Vs1D9P6oFZH_1uY',
    appId: '1:78588377384:android:9864aabc29745f1a52381d',
    messagingSenderId: '78588377384',
    projectId: 'sahhaapp-6e10d',
    databaseURL: 'https://sahhaapp-6e10d-default-rtdb.firebaseio.com',
    storageBucket: 'sahhaapp-6e10d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCps5X_UaskviW-OCtRU18jCdKda73cjj0',
    appId: '1:78588377384:ios:fc508551d3782b2d52381d',
    messagingSenderId: '78588377384',
    projectId: 'sahhaapp-6e10d',
    databaseURL: 'https://sahhaapp-6e10d-default-rtdb.firebaseio.com',
    storageBucket: 'sahhaapp-6e10d.appspot.com',
    iosBundleId: 'com.example.sahhaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCps5X_UaskviW-OCtRU18jCdKda73cjj0',
    appId: '1:78588377384:ios:fc508551d3782b2d52381d',
    messagingSenderId: '78588377384',
    projectId: 'sahhaapp-6e10d',
    databaseURL: 'https://sahhaapp-6e10d-default-rtdb.firebaseio.com',
    storageBucket: 'sahhaapp-6e10d.appspot.com',
    iosBundleId: 'com.example.sahhaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6dXQG3AWe52nWUkiSjwXSfsfPwj3BR4E',
    appId: '1:78588377384:web:5193470a8b9effc752381d',
    messagingSenderId: '78588377384',
    projectId: 'sahhaapp-6e10d',
    authDomain: 'sahhaapp-6e10d.firebaseapp.com',
    databaseURL: 'https://sahhaapp-6e10d-default-rtdb.firebaseio.com',
    storageBucket: 'sahhaapp-6e10d.appspot.com',
  );

}